### ISSUE TITLE
Ne pas relancer au bout d'une semaine les paiements non validés 

### ISSUE THREAD

**Issue by benchti** [otetard/spip_souscription#22]
1 semaine pour cocher les paiements reçus pas cheque ou virement c'est beaucoup trop court. Dans l'idéal il faudrait pouvoir paramétrer cela. En attendant mieux on supprime la relance pour cheque et virement ( Version 2.4.18) .

**Comment by alternat** [comment]
NB : ça relance aussi en cas d'abandon de panier, si on ne va pas au bout du paiement en ligne

**Comment by Cerdic** [comment]
Avec la v3 du plugin bank, les règlements de type cheque/virement font passer la transaction en statut ```attente``` donc le problème ne peut plus se produire

@alternat : c'est normal de relancer quelqu'un qui n'est pas allé au bout du paiement, c'est le principe. On se dit qu'il lui manquait peut etre sa carte pour finir, ou qu'il a été interrompu, et on lui rappelle que ce serait sympa de finir sa souscription.
