### ISSUE TITLE
Possibilité de faux positifs avec le système anti-« pollution »

### ISSUE THREAD

**Issue by otetard** [otetard/spip_souscription#23]
Depuis le commit eb0efdc8ec922a8f31454ba08d23a5b724ab0d1e, si une personne rempli le formulaire une seconde fois, avec des informations similaires (même montant, même courriel), la seconde souscription n’est pas enregistrées (soupçon de doublon). Nous avons fait face à un faux positif : même courriel, même montant, même campagne, mais prénom/nom différent (deux souscriptions d’un couple).

Il faudrait peut être envisager de comparer le prénom et/ou le nom de famille.

**Comment by Cerdic** [comment]
Ça veut dire qu'ils ont fait leurs souscriptions en parallèle ? La deuxième a été saisie avant que la première ne soit payée ? Car une fois la première payée on a plus de risque. A moins qu'on ait eu une collision avec un autre bug sur le statut de la souscription après paiement ?
Mais ok, oui on peut ajouter nom et prenom en test supplementaire.
