### ISSUE TITLE
Paiements récurents pas de mode de paiement

### ISSUE THREAD

**Issue by mistergraphx** [otetard/spip_souscription#30]
Avec une souscription et un paiement récurent, le formulaire de choix de paiement me retourne aucun moyens de paiements disponibles.

Les modes cheque, virement et paypal sont configurés et fonctionne pour un paiement unique de souscription.

j'utilise bien la dernière version de bank,spip 3.2.3, j'ai testé sur plusieurs installations  

est-ce que vous reproduisez ?
y'a t'il des moyens de paiements non éligibles au paiements récurrents ?

merci de vos suggestions , idées

**Comment by Cerdic** [comment]
Cette question concerne plutôt le plugin bank en fait :)

Seuls quelques moyens de paiement prennent en charge le paiement récurrent - ou du moins la prise en charge n'est implémentée que sur ceux-là, car dans le cas paypal c'est une possibilité technique offerte par l'API paypal mais pas mise en œuvre dans le plugin.

Le fait est que le paiement récurrent est assez complexe à gérer proprement, et source de nombreux bugs potentiels provoqués par les cas aux limites (notifications manquantes, représentées avec un délai, en double, résilitation…)

Du coup je ne l'ai implémenté qu'avec les méthodes de paiement pour lesquels j'avais une application réelle dans la vraie vie sous la main pour pouvoir debug et maintenir dans le temps (parce qu'en plus certains presta ont le mauvais gout de changer des choses en cours de route, plus ou moins sans prévenir, ce qui veut dire qu'une implémentation doit être testée en continue pour assurer son fonctionnement)
Les 2 implémentations que je suis en prod sont donc Payzen et Paybox.

(Cela dit, je vois que j'avais aussi implémenté le paiement récurrent avec Stripe, mais typiquement là je n'ai pas eu l'occasion de le mettre à l'épreuve en production)

Les méthodes qui proposent le paiement récurrents l'explicitent clairement dans leur configuration, car on peut choisir de les utiliser uniquement pour le paiement récurrent par exemple

**Comment by Cerdic** [comment]
(du coup je ferme ici, si on doit poursuivre la discussion c'est sur bank)

**Comment by mistergraphx** [comment]
Merci de ta réponse rapide.

Juste pour préciser ici le pourquoi je souhaiterais utiliser une récurence (car peut être n'est ce pas la meilleur solution) …

j'ai toujours utilisé en paiement unique, mais la j'ai une demande tordue ou ils veulent la relance pour les souscriptions adhésions  a  - 30,15,0
les relances sont prévues dans le plugin mais que pour les paiement récurents avec un recurence arbitraire a 1 mois
et pas de relances prévues pour le mode paiement unique
donc plutot que de réécrire tout,le système de notification relance je me disait que je pourrais faire une récurence tout les ans (12mois) et hop c'est bon.

Dans mon idée et si j'ai bien saisie le code actuel il suffirait de rendre paramétrable la récurrence en nombre de mois, pour bénéficier de tout le sytème de relance actuel.

**Comment by Cerdic** [comment]
ah oui mais non, oublie :)

En fait ce qui n'est peut-être pas très clair, c'est que le paiement récurrent n'est pas un paiement unique qui est déclenché par le plugin/SPIP, mais un mécanisme automatique qu'on met en place chez le prestataire de paiement et qui fonctionne tout seul. En particulier il n'y en a pas beaucoup qui permettrait un paiement tous les 12 mois (seul le SEPA le pourrait), ils fonctionnent tous sur une base mensuelle plus ou moins implicitement.

Donc si tu as besoin de notifications de rappel c'est là dessus qu'il faut bosser, pas essayer de biaiser avec les paiements récurrents

**Comment by mistergraphx** [comment]
Bon et bien au boulot ^^ 

Merci des explications effectivement ça parait logique on est plus sur un prélèvement récurent, que un acte de paiement direct.
